### PR TITLE
ContentDiscovery

### PR DESCRIPTION
**Pull request by halseth**
Created a ContentDiscovery module that uses flooding of the network to discover hosts of given hash.

One major flaw as of now: When an actual host receives this message, it gets the peerJS id of the requester, but can only send the content announcement back to the requester if already connected to it. This must be sorted out obviously.

### CODE REVIEW

**Comment by halseth** [comment]
I would love comments on the usage of promises and the approach I took to testing :)

**Comment by ryanxcharles** [comment]
Great work. I briefly reviewed, and note that indentation should be 2 spaces, not tabs. We're using "js standard" which you can install with "npm install -g standard" and then run "standard" to see formatting errors. It will warn about using tabs instead of spaces.

**Comment by willy-b** [comment]
### StandardJS
Thankfully you can run "standard --format" to *automatically* fix most style errors. If it weren't for this I would go crazy :-) .

## Tests
Starting with tests, these are awesome. 
You asked for feedback, so here are my comments:

### Use describe to group tests by Object and Method
  We are using describe to describe objects and methods in the "object"/"@staticMethod" / "#instanceMethod" notation, and then using "it('should do blah blah',...)" to give the expectations on that entity. So your use of "it" is consistent but I am rewriting some of the tests to be consistent.

  For example "notHandleOwnMessage", "handleOtherMessage", etc should just be under "#handleContentDiscoveryRequest" since they describe expectations on ContentDiscoveryRequest.prototype.handleContentDiscoveryRequest

### Use q.promised / promise.then() 
It seems we're settling on using promise.then() / promise.catch() / q.promised() instead of deferred.resolve()/deferred.reject()/q.defer(). 

  I myself used the deferred/promise pattern in our browser side code (index.html) and am more familiar with it from jQuery / underscore.deferred, but Q is really nice. But Ryan is using the then() style everywhere so I'm trying to be consistent. 

  You can wrap a function with q.promised (e.g. q.promised(function (input) { return input; }) ) and get a new async function which returns a promise. You can then use .then() to pass a callback to be executed when it finishes and exceptions you throw will reject the promise. See my changes to your PR (when I push them) for a detailed example.

Awesome stuff. Still playing with it, will merge this afternoon

**Comment by willy-b** [comment]
Working on this merge in my fork, branch "merging-johans-content-discovery":
https://github.com/willy-b/datt-node/tree/merging-johans-content-discovery

**Comment by halseth** [comment]
Nice, Willy! Seems you did most of the cleanup in your branch.

If you could have a look at Datt.prototype.sendMessage method, I didn't know how to use q in this case. Atm it is just waiting for an array of 1 promise, which is a bit dirty...

**Comment by willy-b** [comment]
Johan's demo is of content which references other content. Like an html page that references images stored elsewhere, he has you create  a piece of content that references (and loads) other pieces of content. 

Screenshot which really doesn't do this justice below
verycooljohan

**Comment by willy-b** [comment]
We need to pull Johan's work in. Ryan, do you have any changes you want before we do?

**Comment by ryanxcharles** [comment]
Great work. Notes:

- There shouldn't be so many merge commits. If you're building on an outdated branch and you need to pull in changes from master, the way to do that is with something like "git pull --rebase origin master", which will place all your commits on top of master. That keeps the history linear, which is way easier to dissect when things go wrong than a super complicated nonlinear history with tons of merges.

- "datt" depends on contentDiscovery, and contentDiscovery takes a "datt", so in effect they depend on each other. In general I'm not a fan of this type of architecture. It should be possible to architect things where dependencies flow in a tree, with no circular dependencies. Hierarchical dependencies makes code a lot easier to understand and debug. Code where everything depends on everything else is a nightmare to debug. Instead of calling datt methods from within contentDiscovery, you should return data that is used by datt. Either that or just put the methods on datt.prototype. You would also have an easier time testing your code if you did this, since you wouldn' tneed to mock "datt".

- On an related note, lib/datt.js should really be called "network" or "net" or "p2p" or something else other than "datt", although that has nothing to do with this PR.

- The last contentDiscovery test fails for me ("should throw an error if it cannot send announcement") because contentDiscovery.handleContentDiscoveryRequest uses the "datt" object when actually it should be using "datt2".

**Comment by willy-b** [comment]
Re your side note: Agree on factoring out much of Datt into a "Network"
module, was looking into it today, but will be a while before it is done.

**Comment by halseth** [comment]
Thanks!
* I will try to do rebases next time!
* I very much agree with you on this. We should probably change this to using event emitters or something instead (emit events when different messages are sent/received). My thought was that the ContentDiscovery module should be easy to rewrite completely into using a DHT instead, so I did not want datt.js to assume anything about ContentDiscovery. How to solve this?
* Probably, yeah.
* Pushed a fix.

I also realized now that everything I have pushed after I initiated the PR (the UI demo among other things) automatically gets included in this PR. I should probably start using more branches than just master...

**Comment by halseth** [comment]
Also, adding to the second point:
If we don't send a datt object to contentDoscovery, what is the best way to mock, say, a failing send?

**Pull request merged**
